# Generated by Django 5.2.6 on 2025-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
