# Generated by Django 5.2.6 on 2025-10-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_signup_username_alter_signup_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
    ]
