# Generated by Django 5.2.6 on 2025-11-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_for_booking',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
