# Generated by Django 5.2.6 on 2025-11-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_alter_booking_customer_alter_booking_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=10),
            preserve_default=False,
        ),
    ]
